ignore:
  # This vulnerability does not affect this project as we do not instantiate a rekor client
  - vulnerability: GHSA-2h5h-59f5-c5x9

  # This vulnerability does not affect this project as we do not instantiate a rekor client
  - vulnerability: GHSA-frqx-jfcm-6jjr
