name: install-tools
description: "Install pipeline tools"

runs:
  using: composite
  steps:
    # used by goreleaser to create SBOMs
    - uses: anchore/sbom-action/download-syft@0b82b0b1a22399a1c542d4d656f70cd903571b5c # v0.21.1
