name: save-logs
description: "Save debug logs"

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: debug-log
        path: /tmp/maru-*.log
