name: save-logs
description: "Save debug logs"

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: debug-log
        path: /tmp/maru-*.log
