name: save-logs
description: "Save debug logs"

runs:
  using: composite
  steps:
    - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7.0.2
      with:
        name: debug-log
        path: /tmp/maru-*.log
