name: setup-go
description: "Setup Go binary and caching"

runs:
  using: composite
  steps:
    - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
      with:
        go-version: 1.21.x
