name: Validate Schema
on:
  pull_request:

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Docs and schemas
        run: make test-schema

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
